### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by yanxi-me** [ejcx/passgo#61]
$ go get -u github.com/ejcx/passgo
src/github.com/ejcx/passgo/vendor/golang.org/x/crypto/nacl/secretbox/secretbox.go:38:2: use of internal package not allowed

**Comment by ejcx** [comment]
Thanks. Yeah this is broken. Instead you should run `dep ensure` on the project, and it will build properly.

**Comment by dmitshur** [comment]
The [README instructions](https://github.com/ejcx/passgo#getting-started-with-passgo) only mention the `go get -u github.com/ejcx/passgo` step. Should the extra `dep ensure` step be documented then?

Additionally, @ejcx, are you considering changing this project to use Go modules? That would make it possible to not require an additional tool to build. I gave it a quick try, and didn't spot any immediate issues:

<details><br>

```
passgo $ export GO111MODULE=on
passgo $ go mod init
go: creating new go.mod: module github.com/ejcx/passgo
go: copying requirements from Gopkg.lock
passgo $ cat go.mod 
module github.com/ejcx/passgo

go 1.12

require (
	github.com/atotto/clipboard v0.1.1
	github.com/inconshreveable/mousetrap v1.0.0
	github.com/spf13/cobra v0.0.3
	github.com/spf13/pflag v1.0.3
	golang.org/x/crypto v0.0.0-20190222235706-ffb98f73852f
	golang.org/x/sys v0.0.0-20190222171317-cd391775e71e
)
passgo $ go test ./...
?   	github.com/ejcx/passgo	[no test files]
?   	github.com/ejcx/passgo/edit	[no test files]
ok  	github.com/ejcx/passgo/generate	(cached)
?   	github.com/ejcx/passgo/initialize	[no test files]
?   	github.com/ejcx/passgo/insert	[no test files]
ok  	github.com/ejcx/passgo/pc	(cached)
?   	github.com/ejcx/passgo/pio	[no test files]
?   	github.com/ejcx/passgo/show	[no test files]
passgo $ 
```

</details>

**Comment by ejcx** [comment]
If you would like to migrate the project to Go Modules I would merge that PR! I would appreciate that.

**Comment by dmitshur** [comment]
@ejcx Would you be okay with me dropping the vendor directory as part of the change, or would you prefer to continue to keep it?

By default, the vendor directory doesn't get used when building in module mode (see https://golang.org/cmd/go/#hdr-Modules_and_vendoring), so we'd have to modify the build instructions to use something like `go build -mod=vendor` to make use of it. Module mode already provide reproducible builds (via minimal version selection) and verification of dependencies (via checksums in the go.sum file), so the user experience shouldn't change.

If users report problems not being able to fetch dependencies because they're removed from origin and unavailable via module proxies, it would make sense to consider re-adding the vendor directory at that time. But my default preference is by default to not include it until there's a concrete need. What are your thoughts?

**Comment by ejcx** [comment]
I have no issue killing off the vendor directory. This project was started back when I had `GO15VENDOREXPERIMENT` in my bashrc and I haven't given it too much love besides setting the project up with `dep` 6 months ago.
